from tkinter import *

window = Tk()
window.geometry("400x400")
window.title("Age calculator app")
lb = Label(text="Welcome to age calculator app",height=1,width=300)
lb2 = Label(text="Enter your name",height=1,width=300)
ent = Entry()
lbl3 = Label(text="enter your birth year")
ent2 = Entry()
lbl4 = Label(text="Enter your birth mounth")
ent3 = Entry()
lbl5 = Label(text="enter your birth day")
ent4 = Entry()
def cal():
    name = ent.get()
    year = int(ent2.get())
    result = 2025 - year
    lbr.config(text= f"Current {name} age is {result}")

lbr = Label(text="")
btn = Button(text="Calculate",command= cal,relief=SUNKEN)
lb.pack()
lb2.pack()
ent.pack()
lbl3.pack()
ent2.pack()
lbl4.pack()
ent3.pack()
lbl5.pack()
ent4.pack()
btn.pack()
lbr.pack()
window.mainloop()