from tkinter import *
def mutiply():
     num1 = int(user_entry.get())
     num2 = int(user_entry2.get())
     result = num1 * num2
     result_label.config(text=f"Result: {result}")
window = Tk()
window.geometry("500x500")
window.title("Mutiply program")
lb = Label(text="Welcome to the mutiply program",height=1,width=300)
lb2 = Label(text="enter the first number",height=1,width=300)
user_entry = Entry()
lb3 = Label(text="enter the second number",height=1,width=300)
user_entry2 = Entry()
btn = Button(text="Begin",command=mutiply,height=1,bg="blue",fg="white")
result_label = Label(text="", height=1, width=500,)
lb.pack()
lb2.pack()
user_entry.pack()
lb3.pack()
user_entry2.pack()
btn.pack()
result_label.pack()
window.mainloop()